name_dict:
    id : 10
    nametag: 'cam_original_trial_10_'
    save_name: 'final_model.pth'
    f_ppi : {'name': 'StandardScaler'} 
    
data_dict:
    training_expt : "/ocean/projects/ees240018p/gmooers/Regridding/Training_Data/CAM_Trial_Data_TTTTFTF_Train.nc"
    test_expt : '/ocean/projects/ees240018p/gmooers/Regridding/Training_Data/CAM_Trial_Data_TTTTFTF_Train.nc'
    save_path: '/ocean/projects/ees240018p/gmooers/Investigations/Model_Performance/' #TODO: change
    weights_path : null # or path
    single_file: '/ocean/projects/ees240018p/gmooers/Regridding/Regridded_Data/regridded_DYAMOND2_coars_9216x4608x74_10s_4608_20200229230000_0000353880.atm.3D_resolved.nc4'
    f_ppi : {'name': 'StandardScaler'} # scaling name left over from JN -- not sure if necessary
    o_ppi : {'name': 'StandardScaler'} # scaling name left over from JN -- not sure if necessary
    levels : 49
    do_poles : True
    input_vert_vars : ['Tin','qin','terra','sfc_pres']   
    output_vert_vars : ['Tout', 'T_adv_out','q_adv_out','q_auto_out','q_sed_flux_tot']
    rewight_outputs : True 
    training_data_volume: 100
    test_data_volume: 100
    data_chunks: {'sample': 1024, 'lat': 426, 'lon': 768, 'z': 49}
    dtype_size: 4
    memory_fraction: 0.75

nn_dict:    
    do_nn : True
    batch_norm : False
    epochs: 7
    n_layers: 5
    lr: 0.0000001
    min_lr: 0.0002
    max_lr: 0.002
    lr_redux_factor: 10
    step_size_up : 4000
    batch_size : 1024
    n_trn_exs : 16000000 
    dropoff : 0.02
    neural_network_name: "CustomNet"
    layer_sizes: [128, 128, 128, 128, 128]
    activation_function: ReLU  # Name of the activation function class
    criterion: MSELoss  # Name of the loss function class
    optimizer: Adam      # Name of the optimizer class
    num_workers: 1
    cycle_momentum: False
    torch_thread_number: 10

post_processing_dict:
    only_plot : False
    plotting_path: '/ocean/projects/ees220005p/gmooers/Figures/NN_offline_figs/'

