filepath: "/ocean/projects/ees240018p/gmooers/Regridding/Regridded_Data/*00003**.nc4"
savepath: "/ocean/projects/ees240018p/gmooers/Regridding/Training_Data/"
levels: 49
ground_levels: 1
my_name: "CAM_Test_Data_"
rewight_outputs: False
file_start: 0
file_end: 160
shuffle: True
subset: False

flag_dict:
  Tin_feature: True
  qin_feature: True
  predict_tendencies: True
  skt: False
  land_frac: True
  sfc_pres: True
  cos_lat: False
  grid_cell_area: True